services:
  percona:
    image: percona/percona-server:8.0
    container_name: percona-db
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - percona_data:/var/lib/mysql
      - ./init/percona-init.sql:/docker-entrypoint-initdb.d/percona-init.sql

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql

volumes:
  percona_data:
  postgres_data: